name: Update :help Search Index

on:
  # twice per month (4:35 at the 2nd and 15th of the month)
  schedule:
    - cron: "35 4 2,15 * *"

  # triggering manually
  workflow_dispatch: {}

  # when this file or the script for re-indexing is changed
  push:
    branches:
      - main # prevents triggering on temporary branches created when making a release
    paths:
      - .github/workflows/update-help-index.yml
      - .github/help-index/create-index.sh

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update :help Search Index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
        run: |
          zsh ./.github/help-index/create-index.sh
          exit $? # inherit exit code
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: updated `:help` index"
